### PR TITLE
Major refactoring of SP_test

### PR DESCRIPTION
**Pull request by ghost**
The functional changes are as follows:
- Uses a mock IdP instead of a fully functioning IdP. This allows much greater flexibility in testing, e.g. it allows you to test the SP's reaction to a malicious or broken IdP. The mock IdP will allow you to return any SAML Response XML in the appropriate manner.
- Create a lot of builder classes which can be used to generate SAML XML. This allows us to define the metadata and the responses in the test case or test suite itself, making them much more verifiable. It also means that the people creating the test cases only need to know about SAML, not about how saml2test works.
- Requires much less configuration from the user. No more IdP configuration required since the mock IdP is used and any unnecessary configuration options were removed
- Logging can now be configured using the dict specifications from python's logging.config module. Allows much more fine-grained control over logging.
- Changed the test case specification format to allow more test cases to be run
- Changed the test result format so it better reflects the new test case specification
- Restructured the modules
- Removed all unnecessary code
- Added better recognition for successful logins. It is now user-configurable and can match against HTTP status codes, session cookies and page content.

Though this breaks backwards-compatibility for sp_test, the idp_test should still work exactly the same. 

The SP_test should also still have the same functionality available as before, but usually with a different name or format. The only limitation is that only the HTTP-Redirect and HTTP-POST bindings are implemented for the mock IdP. However, sp_test has been refactored in such a way that this can be added later on without any problems. I added TODO comments wherever this applies. The HTTP-Redirect and POST bindings are fully functional though. I have tested this extensively.

I added a separate HOWTO in the doc folder with detailed instructions on how this new sp_test can be used. It should provide sufficient information on usage, but the code itself also has plenty of documentation. 

I hope this gets merged without any problems. I think this refactoring should make it much easier to create test cases for saml2test as well as make the code more maintainable.

### CODE REVIEW

**Comment by rohe** [comment]
Great work !
Started to go through the changes, will take some time :-)

I've noticed in some cases that you have refrained from using methods
that already exist in pysaml2. 
Most noticeably when it comes to constructing messages.
Is that by design or ... ?

31 mar 2014 kl. 19:15 skrev rmokiem-topdesk notifications@github.com:

> The functional changes are as follows:
> 
>   • Uses a mock IdP instead of a fully functioning IdP. This allows much greater flexibility in testing, e.g. it allows you to test the SP's reaction to a malicious or broken IdP. The mock IdP will allow you to return any SAML Response XML in the appropriate manner.
>   • Create a lot of builder classes which can be used to generate SAML XML. This allows us to define the metadata and the responses in the test case or test suite itself, making them much more verifiable. It also means that the people creating the test cases only need to know about SAML, not about how saml2test works.
>   • Requires much less configuration from the user. No more IdP configuration required since the mock IdP is used and any unnecessary configuration options were removed
>   • Logging can now be configured using the dict specifications from python's logging.config module. Allows much more fine-grained control over logging.
>   • Changed the test case specification format to allow more test cases to be run
>   • Changed the test result format so it better reflects the new test case specification
>   • Restructured the modules
>   • Removed all unnecessary code
>   • Added better recognition for successful logins. It is now user-configurable and can match against HTTP status codes, session cookies and page content.
> Though this breaks backwards-compatibility for sp_test, the idp_test should still work exactly the same.
> 
> The SP_test should also still have the same functionality available as before, but usually with a different name or format. The only limitation is that only the HTTP-Redirect and HTTP-POST bindings are implemented for the mock IdP. However, sp_test has been refactored in such a way that this can be added later on without any problems. I added TODO comments wherever this applies. The HTTP-Redirect and POST bindings are fully functional though. I have tested this extensively.
> 
> I added a separate HOWTO in the doc folder with detailed instructions on how this new sp_test can be used. It should provide sufficient information on usage, but the code itself also has plenty of documentation.
> 
> I hope this gets merged without any problems. I think this refactoring should make it much easier to create test cases for saml2test as well as make the code more maintainable.
> 
> You can merge this Pull Request by running
> 
>   git pull https://github.com/rmokiem-topdesk/saml2test master
> Or view, comment on, or merge it at:
> 
>   https://github.com/rohe/saml2test/pull/26
> 
> Commit Summary
> 
>   • Refactoring
>   • Forgot some documentation
>   • Allow _name variable for a Check class to be used in the test results
>   • Merge branch 'master' of https://github.com/rohe/saml2test into documentation
>   • Corrected import statement for client
>   • Added docstring
>   • Fixed imports
>   • Made logging conform to Python standards
>   • Removed tmp file
>   • Refactoring
>   • More refactoring
>   • Some minor PEP-8 fixes
>   • More refactoring
>   • Added interaction configuration to IdP config for SP tests
>   • added JSON serialization method, which allows you to directly output the
>   • updated documentation
>   • Removed unnecessary modules
>   • added incompatibility notification
>   • removed config, since it is no longer required
>   • Created an abstract class that classes in the test suites should inherit
>   • Implemented some basic tests for the SAML2Int profile
>   • Major refactoring (breaks backwards compatibility)
>   • Changed retrieval of saml request message
>   • Started with creating Response tests
>   • Minor changes
>   • Created builders for generating a minimal metadata document
>   • Created builders required for Response
>   • Completed SP_test refactoring
>   • Added some documentation
>   • Merge branch 'noIdPrequired'
>   • SP howto updated
> File Changes
> 
>   • M doc/conf.py (29)
>   • R doc/howto_idp_test.rst (140)
>   • A doc/howto_sp_test.rst (207)
>   • M doc/index.rst (3)
>   • M script/idp_testdrv.py (2)
>   • M script/sp_testdrv.py (12)
>   • M src/idp_test/**init**.py (5)
>   • D src/idp_test/tmp.py (226)
>   • M src/saml2test/**init**.py (45)
>   • M src/saml2test/check.py (25)
>   • M src/saml2test/interaction.py (5)
>   • A src/saml2test/log_configuration.py (38)
>   • A src/saml2test/saml_builders/**init**.py (69)
>   • A src/saml2test/saml_builders/metadata_builders.py (524)
>   • A src/saml2test/saml_builders/request_builders.py (18)
>   • A src/saml2test/saml_builders/response_builders.py (1395)
>   • M src/saml2test/status.py (34)
>   • M src/sp_test/**init**.py (314)
>   • D src/sp_test/base.py (472)
>   • D src/sp_test/check.py (65)
>   • A src/sp_test/client.py (758)
>   • M src/sp_test/test_suites/SAML2Int.py (463)
>   • M src/sp_test/test_suites/SAMLProf_SingleLogout.py (4)
>   • M src/sp_test/test_suites/SAMLProf_WebSSO.py (4)
>   • M src/sp_test/test_suites/**init**.py (35)
>   • A src/sp_test/test_suites/baseTestSuite.py (245)
>   • M src/sp_test/test_suites/basicTests.py (236)
>   • D tests/sp_test/config.py (91)
>   • M tests/sp_test/targetsp.py (107)
>   • A tests/xsd/saml-schema-assertion-2.0.xsd (283)
>   • A tests/xsd/saml-schema-metadata-2.0.xsd (337)
>   • A tests/xsd/saml-schema-protocol-2.0.xsd (302)
>   • A tests/xsd/xenc-schema.xsd (135)
>   • A tests/xsd/xml.xsd (287)
>   • A tests/xsd/xmldsig-core-schema.xsd (308)
> Patch Links:
> 
>   • https://github.com/rohe/saml2test/pull/26.patch
>   • https://github.com/rohe/saml2test/pull/26.diff
> —
> Reply to this email directly or view it on GitHub.

-- Roland
"Education is the path from cocky ignorance to miserable uncertainty.” - Mark Twain

**Comment by ghost** [comment]
Hey, thanks for letting me know. Sorry for taking so long to answer (and for writing such a long answer). 

I did create my own builders to construct SAML messages by-design. This was part of the whole idea of using a mock IdP instead of a real one. The following points led me to do this:
- I couldn't easily find the methods to construct SAML messages in pysaml2 and it didn't seem like a good idea for everyone who wants to write test cases for saml2test to also need to be intimately familiar with pysaml2 (or at least more familiar with it than I currently am). A possible workaround for this would be to get some kind of interface in pysaml2 but that would just end up extending pysaml2 for something it wasn't made for.
- I wanted the construction of the SAML messages to reflect the original XML of a SAML message. These builders should also allow us to do all kinds of weird things with the SAML messages, which should provide much more flexibility in what we can test. 
- Having the entire SAML message visible in your test cases also allows anyone to easily verify a test case. This would be very useful, since a test result means nothing if the test case can't be verified. This is somewhat related to the next point.
- Using pysaml2 as testing backend would require that pysaml2 is entirely compliant with the SAML specifications. This is something that is not easily verified, since you can't test it with saml2test using pysaml2 as testing backend. And even if it is entirely compliant with SAML specifications, this would mean that we can't test any scenario's where system entities interact with other non-compliant (or less-compliant) system entities. 
- These builders ultimately just deliver the entire SAML message in XML format as a string. This means that anyone writing a test case can just ignore these builders and use their own XML in the test cases. This should improve the flexibility of the test cases and makes it easier to write test cases. 

So in short, the reasoning for this was mainly based on improving testing flexibility and verifiability, as well as making it easier to write test cases.

I should still mention that the builders aren't yet complete. Only the response builders are complete, but it shouldn't be too much work to add the rest. The only thing that would still be difficult to implement, is XML Encryption. I haven't found a python library that implements this yet. I did implement the signing part already, using the python library, https://github.com/leifj/pyXMLSecurity, which seems to be aimed at SAML as well.

If you have any other questions or feedback, let me know. I think the easiest way to understand the main changes I made, is to read the SP HOWTO that I wrote. That should cover the biggest part of it, beacuse I pretty much rewrote everything in sp_test. It should be easier to just look at the current code, instead of the changes I made.

**Comment by ghost** [comment]
Haven't heard anything more about this. Is there something that needs to be fixed before it can be merged? Or is something unclear?

**Comment by rohe** [comment]
Sorry it’s taken me such a long time to get back to you on this.
Lots of traveling and a really bad cold/flu are part of the reasons.
The other thing is that I needed time to consider your approach and compare it with mine.

23 maj 2014 kl. 19:33 skrev rmokiem-topdesk notifications@github.com:

> Haven't heard anything more about this. Is there something that needs to be fixed before it can be merged? Or is something unclear?

No nothing is unclear, it’s more the question about how to do this testing thing.
You’re going in one direction that I’m not completely happy with.

Sure your proposal allows anyone to write test cases directly in XML but that doesn’t mean anything if the test is not firmly planted in the SAML specification. And who is going to verify that ?

If you couldn’t easily find the methods to construct SAML messages in pysaml2 that I would say is a documentation issue
and should be remedied as such.

Proofing that any implementation is compliant with the standard is not easy.
Doing the same work with OpenID Connect we agreed that the only way to do this is to test multiple implementations agains
at least one, preferably against many, other. So it’s a community effort that defines what the standard actually says.
There is no higher court :-) we can turn to, it’s all about consensus.

And finally I would argue that it’s better to base the test tool on an implementation that seeks to be complete and fully compliant (like pysaml2) and can be tested as such, either with the test tool or at F2F interop events, then to base it on code/messages that will never be used outside the test tool.

So I’ve decided to not merge your proposal with saml2test since it takes the project down a path I don’t want to go.

-- Roland
"Education is the path from cocky ignorance to miserable uncertainty.” - Mark Twain

**Comment by ghost** [comment]
While I respect your decision not to merge this PR, I'd still like to explain my reasoning behind this direction of testing. Specifically, I'd like to argue for using a mocked IdP since that seems to be the main problem.

First off though, I'd like to explain why I would not like to test against multiple implementations. While this is indeed useful to test the compatibility of SP's and IdP's, this would be entirely out of the scope of this testing framework. As I understand it, this testing framework is intended to test SAML entities against the SAML 2.0 specification, not to test compatibility between SAML entities. Additionally, while consensus among the existing implementations do define the "de facto" standard, there is still an actual standard defined for SAML 2.0 that they should all adhere to. I think this is the "higher court" that we should turn to. 

This brings me to the use of PySAML2 as testing backend for this testing framework. My main problem with this is actually the same as the problem you have with writing the XML in test cases. "Who is going to verify this?" While I am confident that you and everyone working on PySAML2 have carefully implemented SAML entities that should be entirely SAML 2.0 compliant (and it may well be SAML 2.0 compliant), there is no way to guarantee this and no way to verify this. PySAML2 can not be tested with this testing framework while it still uses PySAML2 as testing backend. So you would need to test PySAML2 independently, using a different testing framework which doesn't use PySAML2 as backend, to make sure it is SAML 2.0 compliant and you would need to do this for every version of PySAML2. However, there is no other testing framework we can use to test PySAML2 against the SAML 2.0 specifications, since that is what we are implementing here in the first place. So the problem of documentation in PySAML2 is actually not the issue here, it was simply an indication of the testing framework's dependency on PySAML2.

So now my reasons for using a mocked IdP. The main reason is actually that it makes it easier to verify the tests. The basis for these tests is the SAML 2.0 specification and the SAML messages in the tests can be directly related to parts of that specification. This direct relation makes it easier to verify that the tests correctly test the SAML 2.0 specification. The tests can be written by anyone but should ultimately be contributed back to the testing framework. This allows anyone familiar with the SAML 2.0 specification to verify these tests, with only minimal knowledge about the testing framework. So to answer your question about who is going to verify the tests, anyone who uses the testing framework can verify it.

As for your argument about basing my tests on SAML messages that will never be used outside the testing framework, I think this is actually quite normal and even required for any test. After all, a specification describes how software should behave and a test should check if the software indeed behaves that way. To do this, you need to trigger that behavior in the software (the input, e.g. by sending a SAML message) and then verify that the software behaves as defined in the specification (the output, e.g. logged in to SP or received response from IdP). This means that you need to define both the trigger for that behavior (input) and the expected response (output) in your test. So any test should always contain both the input and the output in order to correctly test your specification. This input and output will obviously only be used in your tests so there is no reason to try to use it outside the testing framework.

Another benefit of the mocked IdP, is that it is easily possible to test the SAML entity's reaction to a non-compliant SAML entity. This allows for extensive testing of a SAML entity's error handling and failure responses, which should also conform to SAML 2.0 specifications but can also be used for stability tests. This can obviously not be done with a SAML 2.0 compliant SAML entity because it requires a SAML entity that is not SAML 2.0 compliant. This would currently require changing  your backend to yet another SAML entity of which you know that it is not SAML 2.0 compliant and that it fails in the desired way (which seems infeasible).

Having the SAML messages defined in the tests themselves should also make it easier to change the tests if and when the specifications are changed. This should have a minor impact on the testing framework as a whole. 

So as I mentioned in an earlier comment, using a mocked IdP should improve testability, verifiability and maintainability. Of course, if you still do not want to use a mocked IdP, I respect that decision. I am currently still working on improving the SAML builders and providing convenience methods for easily creating these SAML messages, so I will continue to work on this in my forked repository but I will not create Pull Requests for this since it is based on the work in this PR. 

I hope to hear your response soon.

**Pull request closed without merging**
